### ISSUE TITLE
RE-CAPTCHA issues

### ISSUE THREAD

**Issue by j-ro** [unitedstates/contact-congress#1434]
Anyone else having Re-Captcha issues recently? I know this is something we've feared...

I'm not seeing the new style ones on any forms yet, but the old style ones seem to be returning nearly impossible images through phantom-js, like this:

https://can2-dev.s3.amazonaws.com/development/captchas/1b0209b62f9a37d9adc286fde8.png

It's basically gibberish, and I can never get it right. But, when I load the page directly (in this case, http://mcclintock.house.gov/contact/email-me, zip 95746, 8501), the captcha I get is much more human friendly every time, making me think Re-Captcha knows phantom-js isn't human and is serving nearly impossible captchas on purpose.

Anyone else see this?

**Comment by crdunwel** [comment]
Rand Paul seems to have started to use the new style Re-Captcha ....

http://www.paul.senate.gov/connect/email-rand

Do we have a way of handling these yet?

**Comment by j-ro** [comment]
Oy...I thought he had taken such a step forward by taking the captcha off his form...

What happens if you click the div to check that box in yaml? Does it think we're a spammer?

**Comment by crdunwel** [comment]
Figured I'd ask first in case somebody has cooked up something clever. Let me try that now.

**Comment by j-ro** [comment]
Nope, this is the first. We were kind of fearing this day...

**Comment by sinak** [comment]
:sob:

**Comment by crdunwel** [comment]
So .recaptcha-checkbox-checkmark is in an iframe - possible to select elements within iframes?

**Comment by j-ro** [comment]
hm....no, don't think it is. Sina?

**Comment by sinak** [comment]
I'm not sure. How about a snippet like this one: https://github.com/unitedstates/contact-congress/blob/7c82181c94d8a4aa11a79bf560bf71c439622bde/support/recaptcha-noscript.yaml

**Comment by sinak** [comment]
That looks like it's actually visiting the URL, not sure if it'll work.

**Comment by j-ro** [comment]
Yeah, that's not going to work. Maybe iframes will work, not sure -- I mean, we are running a browser, and browsers can hit iframes themselves, but really not sure how that's all going to work when passed through javascript. I doubt it'll work though...

**Comment by crdunwel** [comment]
Too bad his site doesn't even work without javascript...

@j-ro we are running a browser so it should be possible to do this somehow. Even if the click doesn't work initially, we can grab the captcha image(s) that come up and send them to the user to be solved. Phantom of the capitol might need to modified to handle this case though....

**Comment by drinks** [comment]
Hi folks!

FWIW, it looks like this might be solvable by grabbing the `k` query param from the iframe source, and supplying it in a `POST` request to `https://www.google.com/recaptcha/api2/userverify` from the same browser session, (so for example, `https://www.google.com/recaptcha/api2/userverify?k=6Ld4GgUTAAAAAKvWFV6QlIupzvQ2_nYZt3WkYHTq` after visiting the form).

The response should be unparseable json that you can string manipulate into an array where index 1 is the value you should dump into the hidden textarea immediately after the iframe (you'll probably have to unhide it before you can select/manipulate it).

I don't have a test env configured, but it looks at a glance like that may do it. There's probably some other factor though bc that seems too easy--no images or anything!

**Comment by j-ro** [comment]
huh...interesting. How would we do that in yaml? Probably can't right now, would require something like https://github.com/EFForg/phantom-of-the-capitol/issues/51

Or https://github.com/unitedstates/contact-congress/issues/1421 so we can select iframes...

**Comment by j-ro** [comment]
and yes, @crdunwel, if we could click that checkbox, even if we're thought to be a spammer then we can get the captcha image after a wait or something, though it may all still be in an iframe...

**Comment by drinks** [comment]
probably would need some set of captcha steps specific to this version of recaptcha that just attempts to solve it automatically right before submit, but you may still be SOL if you can't manipulate the contents of the frame and are presented with an image to solve..

**Comment by j-ro** [comment]
I mean, we could probably even get by with a click command that clicks a certain coordinate relative to the parent -- we could ignore the iframe entirely and just click on some pixel offset relative to the .g-recaptcha div that surrounds the iframe. Then we could take a picture of the iframe parent div to get the captcha image.

**Comment by crdunwel** [comment]
@drinks Wow, could circumventing new style google recaptcha really be that easy? Have others written about this strategy?

@j-ro Yeah, we'd need a way to find selectors in iframes. This seems like it should be possible but @Hainish would probably know more about it.

Either way it seems like we'd need captcha specific steps for this version of recaptcha like @drinks suggests.

**Comment by j-ro** [comment]
@Hainish or @drinks, does anyone have time to work on this? @crdunwel, you too if you want to hack on phantom-dc. My team might, but might not be for a week or so...

**Comment by kthayer424** [comment]
Just an FYI, [here's](https://github.com/NGPVAN/contact-congress/blob/master/members/SWe00074.yaml) an example of how we handled another recaptcha form.

We implemented something similar to [this](https://github.com/unitedstates/contact-congress/issues/1421) issue brought up a while back. This strategy has been working like a charm, it's just a matter of moving between iframes.

Now, trying to handle the case where the new recaptcha serves up a list of pictures to choose from instead of entering in text is a separate problem...

**Comment by j-ro** [comment]
Can you contribute your iframe code back to the phantom-do repo?

**Comment by kthayer424** [comment]
We stopped using congress-forms a little while back and ended up writing our own implementation in C# using phantomjs. It's in the process of being released to the public while we use it, but since it's in C#, no one probably wants it anyway...

However, here's a snippet of what's going on to move between iframes and the parent frame, it's supported on any language:

    if (iframe.Back)
    {
       driver.SwitchTo().Window(driver.WindowHandles.First());
    }
    else
    {
       var element = driver.FindElement(By.CssSelector(iframe.Selector));
       driver.SwitchTo().Frame(element);
    }

**Comment by j-ro** [comment]
Ah cool. Well this is useful too!

**Comment by kthayer424** [comment]
I updated the issue I created a bit if we want to settle on a syntax for describing this action in a yaml and we're open to other suggestions on syntax or how to handle this problem overall. But weaving in and out of iframes as worked so far.

**Comment by j-ro** [comment]
generally seems fine to me -- not sure we actually need the iframe1/parent1 thing, as in, since you can only move in and out of iframes, you probably don't need to give them numbers. So, you move in and out of iframes and use the parent command to go up one level. Like:

```
    - iframe:
      - selector: "[title='recaptcha widget']"
        # now we're in iframe context
    - click_on:
      - value: recaptcha
        selector: ".recaptcha-checkbox"
    - iframe:
      - back: true
        # now we're back to parent
    - wait:
      - value: 2
    - iframe:
      - selector: "[title='recaptcha challenge']"
        # back to iframe context
    - fill_in:
      - name: recaptcha_response_field
        captcha_selector: "body img"
        value: $CAPTCHA_SOLUTION
        selector: "#default-response"
        required: true
    - click_on:
      - value: recaptchaSubmit
        selector: "#recaptcha-verify-button"
    - iframe:
      - back: true
        # and back to parent
```

Potentially, this could do nested iframes, just call the iframe command with a selector twice to move down two levels, and back twice to move back up.

But maybe I'm missing a use case or implementation detail there.

**Comment by kthayer424** [comment]
I only added the `name` property to `iframe` because it seemed like a helpful identifier, but it isn't needed to do anything. But yeah, there was an intention to be able to go N deep into iframes if necessary.

**Comment by j-ro** [comment]
Cool, either way seems good.

I'd suggest this is probably the way to go -- iframe functionality is useful outside of the recaptcha context too.

@drinks, @Hainish, @crdunwel, if you agree, let me know if you have time to work on this. As I noted above, my team might, but wouldn't be until some time next week, so if anyone has time to tackle this sooner, would be great...

**Comment by drinks** [comment]
I might suggest renaming the `iframe` step to more consistent with the existing syntax--since the current step names are cribbed from capybara, I'd recommend borrowing the name of their `within_frame` function, and literally nesting all subsequent steps below it, rather than implementing a `back` to step back out--just return to the main document once the `within_frame` steps are done. I'm afraid I've got no knowledge of the existing stack you guys are using to fill out forms, but I'm happy to provide assistance where I can. Leading any effort on this is going to be beyond my capacity though, I'm afraid.

**Comment by kthayer424** [comment]
I didn't see a way to nest step types together in the existing syntax. How would you nest `fill_in`s and `click_on`s in a step such that when you were finished with them all you'd know to back out of the frame without a breaking change?

**Comment by drinks** [comment]
My (perhaps naive) first instinct might look something like this:
```yaml
steps:
  - do_something:
    ...
  - within_frame:
    selector: "#myIframe"
    steps:
      - click_on:
        ...
      - fill_in:
        ...
  - do_something_else:
    ...
```

There are, of course a couple of assumptions being made, and that's where my naievete may come in. My formageddon implementation was built to ignore any steps that it didn't recognize... essentially iterating over all steps and calling whichever method matched the step name with the supplied params. If the existing state(s) of the art calls methods based on step names instead, they may need to catch exceptions where methods aren't defined. Adding support for recursion like this would require a code change, but any solution will require a code change, right? In the case where a system was unfamiliar with `within_frame` I'd expect it to skip to the next top-level step and ignore the nested ones. Up to the current maintainers how to proceed, but this approach feels most flexible to me.

**Comment by j-ro** [comment]
I agree on the recursion being a bit weird in the schema. We're implementing this now, and I think we're going to do it this way:

```
   - iframe:
      - selector: "[title='recaptcha widget']"
        # now we're in iframe context
    - click_on:
      - value: recaptcha
        selector: ".recaptcha-checkbox"
    - iframe:
      - back: true
        # now we're back to parent
    - wait:
      - value: 2
    - iframe:
      - selector: "[title='recaptcha challenge']"
        # back to iframe context
    - fill_in:
      - name: recaptcha_response_field
        captcha_selector: "body img"
        value: $CAPTCHA_SOLUTION
        selector: "#default-response"
        required: true
    - click_on:
      - value: recaptchaSubmit
        selector: "#recaptcha-verify-button"
    - iframe:
      - back: true
        # and back to parent
```

So, commands move you in and out of an iframe's context.
